#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|fedora)  package_uninstall micro ;;
  ubuntu)              bin_uninstall micro ;;
  *)                   warning "not available for distro:$DISTRO" ;;
esac

say "removing ~/.config/micro"
sudo rm -rf ~/.config/micro
