#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch") package_uninstall micro ;;
  "ubuntu") bin_uninstall micro ;;
esac

say "removing ~/.config/micro"
sudo rm -rf ~/.config/micro
