#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_g_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}

  case "$COMP_LINE" in
    'g b -d'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'g del'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'g co'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'g m'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
  esac
}

complete -F _g_completions g
