#!/usr/bin/env bash

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended
_g_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local comp_line="${COMP_WORDS[*]:1}"

  case "$comp_line" in
    'rename'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'retag'*) COMPREPLY=($(compgen -W "$(git tag 2> /dev/null)" -- "$cur")) ;;
    'b -d'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'del'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'co'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
    'm'*) COMPREPLY=($(compgen -W "$(git branch 2> /dev/null)" -- "$cur")) ;;
  esac
}

complete -F _g_completions g
