#!/usr/bin/env bash

set -e

echo "Installing yarn if necessary"
[[ -x "$(command -v yarn)" ]] || rush get $REPO yarn

echo "Installing asciinema if necessary"
[[ -x "$(command -v yarn)" ]] || rush get $REPO asciinema

echo "installing svg-term-cli"
sudo yarn global add svg-term-cli

