#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

# Versions: https://github.com/postmodern/ruby-install/tags
version=0.8.5

say "uninstalling ruby-install $version"
tmpdir=$(temp_dir)
pushd "$tmpdir"
 
wget -O ruby-install-$version.tar.gz https://github.com/postmodern/ruby-install/archive/v$version.tar.gz
tar -xzvf ruby-install-$version.tar.gz
pushd ruby-install-$version/
sudo make uninstall

popd
popd
rm -rf "$tmpdir"

say "ruby-install uninstalled"