#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for xxxserxxx/gotop"
version=$(get_github_release_version xxxserxxx/gotop)
say "latest version is $version"

if ! is_installed gotop ; then
  say "installing gotop (github)"
  wget -qO ./gotop.deb "https://github.com/xxxserxxx/gotop/releases/download/v$version/gotop_${version}_linux_amd64.deb"
  sudo dpkg -i gotop.deb
  rm gotop.deb

  gotop --version
  say "gotop installation complete"

else
  say "installed version is also $version, no update needed."

fi
