#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)    package_install ctags ;;
  debian|ubuntu)  package_install universal-ctags ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
