#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

if command_exist speedtest ; then
  say "speedtest-cli is already installed"

else
  needs python

  python3 -m pip install speedtest-cli
  speedtest --version
  
fi
