#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/XAMPPRocky/tokei/releases/download/v${version}/tokei-x86_64-unknown-linux-gnu.tar.gz"
  curl -sL "$url" | tar -xzv
  sudo install -m 755 tokei /usr/local/bin/
  popd
}

github_install_helper tokei XAMPPRocky/tokei
