#!/usr/bin/env bash

# Borg can be installed with `sudo apt install borgbackup`
# However, this is not the latest version, so this rush package is:
#
# 1. Installing borgbackup with apt, to get the man pages
# 2. Replacing the binary with the latest release downloaded from GitHub
#

### TODO: Use this when the borg release page contains the correct latest 
### release.
###
### This does not work for the moment, since they released an older version
### after a newer version
# echo "Identifying latest version"
# version=$(curl -s https://api.github.com/repos/docker/machine/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
# echo "Latest version is $version"

### ... so using hardcoded version instead for now
version=1.1.9
echo "Considering latest version 1.1.9 (hardcoded in this rush script)"

echo "Comparing with installed version (if any)"
hash borg 2> /dev/null && borg --version | grep $version > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  echo "Installing borgbackup from apt..."
  sudo apt install borgbackup

  echo "Downloading latest borg from GitHub..."
  curl -# -L https://github.com/borgbackup/borg/releases/download/$version/borg-linux64 > /tmp/borg
  chmod +x /tmp/borg
  sudo mv /tmp/borg /usr/bin/borg

  echo "Done."
  borg --version

else
  echo "Installed version is also $version, no update needed."
  echo "Goodbye."

fi


