#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_uninstall borg ;;
  debian|fedora|ubuntu)  package_uninstall borgbackup ;;
  *)                     warning "not available for distro:$DISTRO" ;;
esac
