#!/usr/bin/env bash
source ../common.sh
say "configuring git"

cp .gitignore_global ~/.gitignore_global

git config --global push.default simple
git config --global color.ui true
git config --global core.editor vi
git config --global core.autocrlf input
git config --global core.excludesfile ~/.gitignore_global
git config --global credential.helper "cache --timeout=21600"

say "git configuration complete"