#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
say "configuring git"

cp .gitignore_global ~/
cp .gitattributes_global ~/

git config --global push.default simple
git config --global color.ui true
git config --global core.editor vi
git config --global core.autocrlf input
git config --global credential.helper "cache --timeout=21600"
git config --global core.excludesfile ~/.gitignore_global
git config --global core.attributesfile ~/.gitattributes_global
git config --global init.defaultBranch master

# virtualbox shared folder stability
git config --global checkout.thresholdForParallelism 999999
git config --global checkout.workers 1
git config --global core.filemode false
git config --global core.preloadindex false
git config --global core.untrackedCache false
git config --global gc.auto 0
git config --global gc.autoDetach false
git config --global index.threads 1
git config --global maintenance.auto false
git config --global pack.threads 1
git config --global --unset-all core.fsmonitor 2>/dev/null || [[ $? -eq 5 ]]
git config --global --unset-all core.fsyncMethod 2>/dev/null || [[ $? -eq 5 ]]
git config --global --unset-all feature.fsmonitor 2>/dev/null || [[ $? -eq 5 ]]

# List of supported hunk header patterns for .gitattributes:
# https://github.com/git/git/blob/master/userdiff.c
# or
# $ man gitattributes (and search for ada)
