#!/usr/bin/env bash
source ../common.sh

say "installing prerequisites"
needs bashrc

say "installing linuxbrew-wrapper (apt)"
sudo apt install -y linuxbrew-wrapper

say "copying ~/.bashrc.d config"
cp brew.bashrc ~/.bashrc.d/

say "running brew setup"
brew

say "brew installation complete"
say "restart your session or source ~/.bashrc"
