#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_uninstall httpie
    ;;
  "ubuntu")
    say "uninstalling httpie"
    sudo python3 -m pip uninstall httpie
    ;;
esac
