#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

needs yarn

say "installing caniuse-cmd (yarn)"
yarn global add caniuse-cmd
say "caniuse installation complete"
say "you may need to restart your session"

