#!/usr/bin/env bash
set -e

RUBY_VERSION=2.6.3

if [[ ! -x "$(command -v rvm)" ]]; then
  echo "RVM is not installed."
  echo "Run 'rush rvm' first."
  exit
fi

if [[ -x "$(command -v ruby)" ]]; then
  echo "Ruby is already installed:"
  ruby --version
  exit
fi

rvm install $RUBY_VERSION

echo "Copying .gemrc"
cp .gemrc ~/.gemrc

echo "Ruby Installed, please run:"
echo "rvm use $RUBY_VERSION --default && gem install bundler"
