#!/usr/bin/env bash
source ../common.sh

version=3.0.1

needs ruby-base rbenv
# shellcheck disable=SC1091,SC1090
source "$HOME/.bashrc.d/rbenv.bashrc"  # in case rbenv was not installed yet

say "installing ruby $version with rbenv"
rbenv install -s "$version"
rbenv global "$version"

say "copying configuration files"
cp .gemrc ~/
mkdir -p ~/.bundle/
cp config ~/.bundle/
ruby -v

say "ruby installation complete"
attention "you may need to restart your session or source ~/.bashrc.d/rbenv.bashrc"
