#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

version=4.0.1

needs ruby-base rv
# shellcheck disable=SC1091,SC1090
source "$HOME/.bashrc.d/rv.bashrc"  # in case it was installed just now

say "installing ruby $version with rv"
rv ruby install "$version"
pushd ~
rv ruby pin "$version"
popd

say "copying configuration files"
cp .gemrc ~/
cp .irbrc ~/
mkdir -p ~/.bundle/
cp config ~/.bundle/
ruby -v

say "ruby installation complete"
attention "restart your session or source ~/.bashrc"
