#!/usr/bin/env bash
source ../common.sh

say "installing slack cli (github)"
sudo wget -qO /usr/local/bin/slk https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
sudo chmod +x /usr/local/bin/slk
slk --version
attention "remember to set the SLACK_CLI_TOKEN environment variable"

