#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    package_uninstall d2
    ;;
  
  debian|fedora|ubuntu)
    bin_uninstall d2
    sudo rm -f /usr/local/share/man/man1/d2.1
    ;;

  *)
    warning "not available for distro:$DISTRO"
    ;;
esac
