#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "ubuntu") package_install librsvg2-bin rsvg-convert ;;
  "arch") package_install librsvg rsvg-convert ;;
esac

rsvg-convert --version
