#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)    package_install librsvg ;;
  fedora)  package_install librsvg2-tools ;;
  ubuntu)  package_install librsvg2-bin ;;
  *)       fail "not available for distro:$DISTRO" ;;
esac

rsvg-convert --version
