#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall librsvg ;;
  debian|ubuntu)  package_uninstall librsvg2-bin ;;
  fedora)         package_uninstall librsvg2-tools ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
