#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)    package_uninstall librsvg ;;
  fedora)  package_uninstall librsvg2-tools ;;
  ubuntu)  package_uninstall librsvg2-bin ;;
  *)       warning "not available for distro:$DISTRO" ;;
esac
