#!/usr/bin/env bash
source ../../common.sh

say "installing prerequisites"
needs bashrc

say "copying ~/.bashrc.d/global.bashrc"
cp global.bashrc "$HOME/.bashrc.d/global.bashrc"

say "my/bashrc installation complete"
