#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing essential rush packages"
needs bashrc
needs dircolors exrc inputrc prompt/dollar-color
needs vi fd less
command_exist alf || rush get "$REPO:alf"

say "bootstrap complete"
attention "you may need to restart your session"
