#!/usr/bin/env bash
source ../../common.sh

if [[ -z "$BUNDLE_GEM__FURY__IO" ]]; then
  warning "Unable to add without BUNDLE_GEM__FURY__IO"
else
  gem sources --add "https://${BUNDLE_GEM__FURY__IO}@gem.fury.io/dannybtsm/"
fi
