#!/usr/bin/env bash
source ../common.sh

install_function() {
  curl -sL "https://github.com/rust-lang/mdBook/releases/download/v$version/mdbook-v$version-x86_64-unknown-linux-gnu.tar.gz" | tar -xzv
  chmod +x mdbook
  sudo mv mdbook /usr/local/bin/
}

github_install_helper mdbook "rust-lang/mdBook"
