#!/usr/bin/env bash
set -e

echo "Identifying latest version"
version=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
echo "Latest version is $version"

# If you want, force a version here
# version=1.1.9

echo "Comparing with installed version (if any)"
hash mdbook 2> /dev/null && mdbook --version | grep $version > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  echo "Downloading mdbook from GitHub..."
  curl -sL https://github.com/rust-lang/mdBook/releases/download/v$version/mdbook-v$version-x86_64-unknown-linux-gnu.tar.gz | tar -xzv
  chmod +x mdbook
  sudo mv mdbook /usr/local/bin/

  echo "Done."
  mdbook --version

else
  echo "Installed version is also $version, no update needed."
  echo "Goodbye."

fi


