version: '3'

volumes:
  localbin:
  home:

services:
  bash:
    image: dannyben/rush
    depends_on: [web]
    volumes: 
    - localbin:/usr/local/bin
    - home:/home/ubuntu/
    environment:
      RUSH_REPO: http://web:3000

  web:
    image: dannyben/alpine-adsf
    volumes: 
    - .:/app
    ports:
    - 3000:3000
