version: '2'

volumes:
  app:
  localbin:
  home:

services:
  bash:
    build: .
    image: dannyben/rush
    depends_on: [web]
    volumes: 
    - app:/app
    - localbin:/usr/local/bin
    - home:/home/bob/
    environment:
      RUSH_REPO: http://web:3000

  web:
    image: dannyben/alpine-adsf
    volumes: 
    - /vagrant/bash/rush:/app
    ports:
    - 3000:3000
