services:
  ubuntu:
    build:
      dockerfile: _dockerfiles/ubuntu.Dockerfile
    image: dannyben/rush-ubuntu-sandbox
    volumes: &rush-repo
    - .:/app/rush-repo

  arch:
    build:
      dockerfile: _dockerfiles/arch.Dockerfile
    image: dannyben/rush-arch-sandbox
    volumes: *rush-repo

  debian:
    build:
      dockerfile: _dockerfiles/debian.Dockerfile
    image: dannyben/rush-debian-sandbox
    volumes: *rush-repo

  fedora:
    build:
      dockerfile: _dockerfiles/fedora.Dockerfile
    image: dannyben/rush-fedora-sandbox
    volumes: *rush-repo

