#!/usr/bin/env bash

printf "Package Index for DannyBen\n\n"

for d in */; do
  infofile="$d/info"
  [[ -f $infofile ]] && printf "%-16s `head -1 $infofile`\n" ${d:0:-1}
done

printf "\nPersonal Packages\n\n"

for d in my/*/; do
  infofile="$d/info"
  [[ -f $infofile ]] && printf "%-16s `head -1 $infofile`\n" ${d:0:-1}
done
