#!/usr/bin/env bash
source ../common.sh

install_function() {
  pushtmp
  url="https://github.com/stepchowfun/toast/releases/download/v${version}/toast-x86_64-unknown-linux-gnu"
  wget -O toast "$url"
  sudo install -m 755 toast /usr/local/bin/
  popd
}

github_install_helper toast stepchowfun/toast
