#!/usr/bin/env bash
source ../common.sh

needs bashrc

say "installing direnv"
case "$DISTRO" in
  "ubuntu") sudo apt install -y direnv ;;
  "arch") sudo pacman -S --noconfirm direnv ;;
esac

say "copying bashrc.d configuration"
cp direnv.bashrc ~/.bashrc.d/direnv.bashrc
