#!/usr/bin/env bash
source ../common.sh

say "installing prerequisites"
needs bashrc

say "installing direnv"
sudo apt install direnv

say "copying bashrc.d configuration"
cp direnv.bashrc ~/.bashrc.d/direnv.bashrc

say "direnv installation complete"
