#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs bashrc
package_install direnv

say "copying bashrc.d configuration"
cp direnv.bashrc ~/.bashrc.d/direnv.bashrc
attention "restart your session or source ~/.bashrc"