#!/usr/bin/env bash
source ../common.sh

install_function() {
  curl -sL "https://github.com/instrumenta/kubeval/releases/download/$version/kubeval-linux-amd64.tar.gz" | tar -xzv kubeval
  chmod +x kubeval
  sudo mv kubeval /usr/local/bin/
}

github_install_helper kubeval "instrumenta/kubeval"
