#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/instrumenta/kubeval/releases/download/v$version/kubeval-linux-amd64.tar.gz"
  curl -sL "$url" | tar -xzv kubeval
  chmod +x kubeval
  sudo mv kubeval /usr/local/bin/
}

github_install_helper kubeval "instrumenta/kubeval"
