#!/usr/bin/env bash
source ../common.sh

needs jq pup recode

say "installing tuxi"
sudo curl -sL "https://raw.githubusercontent.com/Bugswriter/tuxi/main/tuxi" -o /usr/local/bin/tuxi
sudo chmod +x /usr/local/bin/tuxi
