#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "ubuntu") package_install resolvconf ;;
  "arch") package_install systemd-resolvconf ;;
esac

say "copying configuration file"
sudo cp config /etc/resolvconf/resolv.conf.d/head

sudo service resolvconf restart
cat /etc/resolv.conf
attention "reboot may be required"
