#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)    package_uninstall systemd-resolvconf ;;
  fedora)  package_uninstall openresolv ;;
  ubuntu)  package_uninstall resolvconf ;;
  *)       warning "not available for distro:$DISTRO" ;;
esac

attention "reboot is required"
