#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

sudo pacman -Syu --noconfirm && sudo pacman -S --noconfirm --needed \
  base-devel \
  curl \
  gdbm \
  git \
  libffi \
  libyaml \
  ncurses \
  openssl \
  readline \
  wget \
  zlib
