#!/usr/bin/env bash
source ../common.sh

needs bashrc

# Versions: https://github.com/postmodern/chruby/releases
version=0.3.9

say "installing chruby $version"
tmpdir=$(temp_dir)
pushd "$tmpdir"
 
wget -O chruby-$version.tar.gz https://github.com/postmodern/chruby/archive/v$version.tar.gz
tar -xzvf chruby-$version.tar.gz
pushd chruby-$version/
sudo make install

popd
popd
rm -rf "$tmpdir"

say "copying chruby.bashrc"
cp chruby.bashrc ~/.bashrc.d/

say "chruby installed"
attention "restart your session or source ~/.bashrc.d/chruby.bashrc"
