#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)    package_install libfaketime ;;
  debian|ubuntu)  package_install faketime ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
