#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  apt_install_deb "https://github.com/sharkdp/hyperfine/releases/download/v${version}/hyperfine_${version}_amd64.deb"
}

case "$DISTRO" in
  "ubuntu") github_install_helper hyperfine sharkdp/hyperfine ;;
  "arch") package_install hyperfine ;;
esac
