#!/usr/bin/env bash
source ../common.sh

install_function() {
  apt_install_deb "https://github.com/sharkdp/hyperfine/releases/download/v${version}/hyperfine_${version}_amd64.deb"
}

github_install_helper hyperfine sharkdp/hyperfine
