#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/charmbracelet/freeze/releases/download/v$version/freeze_${version}_Linux_x86_64.tar.gz"
  curl -sL "$url" | tar -xzv
  chmod +x "freeze_${version}_Linux_x86_64/freeze"
  sudo mv "freeze_${version}_Linux_x86_64/freeze" /usr/local/bin/
  popd
}

# freeze does not have any version flag, so we only install it if it does not exist
# https://github.com/charmbracelet/freeze/issues/64
# github_install_helper freeze "charmbracelet/freeze"

if command_exist 'freeze'; then
  say "freeze is already installed"
else
  version=$(get_github_release_version "charmbracelet/freeze")
  say "installing freeze $version"
  install_function
  say "freeze installation complete"
fi
