#!/usr/bin/env bash
source ../common.sh

install_function() {
  curl -# -L "https://github.com/kubernetes/kompose/releases/download/v$version/kompose-linux-amd64" -o kompose
  chmod +x kompose
  sudo mv kompose /usr/local/bin/
}

github_install_helper kompose "kubernetes/kompose"
