#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for kubernetes/kompose"
version=$(get_github_release_version kubernetes/kompose)
say "latest version is $version"

if ! is_installed kompose version; then
  say "installing kompose (github)"
  curl -# -L "https://github.com/kubernetes/kompose/releases/download/v$version/kompose-linux-amd64" -o kompose
  chmod +x kompose
  sudo mv kompose /usr/local/bin/

  kompose version
  say "kompose installation complete"

else
  say "installed version is also $version, no update needed."

fi
