#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for rancher/k3s"
version=$(get_github_release_version rancher/k3s)
say "latest version is $version"

if ! is_installed k3s ; then
  say "installing k3s (github)"
  curl -# -L "https://github.com/rancher/k3s/releases/download/v$version/k3s" >/tmp/k3s
  chmod +x /tmp/k3s
  sudo mv /tmp/k3s /usr/local/bin/k3s

  k3s --version
  say "k3s installation complete"

else
  say "installed version is also $version, no update needed."

fi
