#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/asciimoo/wuzz/releases/download/v${version}/wuzz_linux_amd64"
  wget -O wuzz "$url"
  sudo install wuzz /usr/local/bin/
  popd
}

github_install_helper wuzz asciimoo/wuzz
