#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for mikefarah/yq"
version=$(get_github_release_version mikefarah/yq)
say "latest version is $version"

if ! is_installed yq; then
  say "installing yq (github)"
  sudo curl -L "https://github.com/mikefarah/yq/releases/download/$version/yq_linux_amd64" -o /usr/local/bin/yq
  sudo chmod +x /usr/local/bin/yq
  
  yq --version
  say "yq installation complete"

else
  say "installed version is also $version, no update needed."

fi
