#!/usr/bin/env bash
source ../common.sh

install_function() {
  sudo curl -L "https://github.com/mikefarah/yq/releases/download/v$version/yq_linux_amd64" -o /usr/local/bin/yq
  sudo chmod +x /usr/local/bin/yq
}

github_install_helper yq "mikefarah/yq"
