#!/usr/bin/env bash
source ../common.sh

# TODO: Convert this to use github_install_helper when 0.9.0 is live

version=0.9.0-beta1

say "installing docker app v$version"
ostype="$(uname | tr '[:upper:]' '[:lower:]')"
curl -#L --output "/tmp/docker-app-${ostype}.tar.gz" "https://github.com/docker/app/releases/download/v$version/docker-app-${ostype}.tar.gz"
tar xf "/tmp/docker-app-${ostype}.tar.gz" -C /tmp/
mkdir -p ~/.docker/cli-plugins && cp "/tmp/docker-app-plugin-${ostype}" ~/.docker/cli-plugins/docker-app

say "copying bashrc.d configuration"
cp docker-app.bashrc ~/.bashrc.d/

docker app --version
