#!/usr/bin/env bash
source ../common.sh

install_function() {
  sudo curl -L "https://github.com/kubernetes-sigs/kind/releases/download/v$version/kind-linux-amd64" -o /usr/local/bin/kind
  sudo chmod +x /usr/local/bin/kind
}

github_install_helper kind "kubernetes-sigs/kind"
