#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for kubernetes-sigs/kind"
version=$(get_github_release_version kubernetes-sigs/kind)
say "latest version is $version"

if ! is_installed kind ; then
  say "installing kind (github)"
  sudo curl -L "https://github.com/kubernetes-sigs/kind/releases/download/v$version/kind-linux-amd64" -o /usr/local/bin/kind
  sudo chmod +x /usr/local/bin/kind
  kind --version
  say "kind installation complete"

else
  say "installed version is also $version, no update needed."

fi
