#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/bjesus/pipet/releases/download/${version}/pipet-linux-amd64.tar.gz"
  curl -sL "$url" | tar -xzv
  mv pipet-linux-amd64 pipet
  bin_install pipet
  popd
}

github_install_helper pipet "bjesus/pipet"

