#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/bjesus/pipet/releases/download/${version}/pipet-linux-amd64.tar.gz"
  curl -sL "$url" | tar -xzv
  mv pipet-linux-amd64 pipet
  bin_install pipet
  popd
}

if command_exist pipet ; then
  say "pipet is already installed"
else
  version=0.2.2
  install_function
fi

# version flag not provided by pipet
# ref: https://github.com/bjesus/pipet/issues/2
# when it is, we can use the below function instead of the condition above
# github_install_helper pipet "bjesus/pipet"

