#!/usr/bin/env bash
source ../common.sh

install_function() {
  # Downloads are here: https://wkhtmltopdf.org/downloads.html
  distro="bionic"
  url="https://github.com/wkhtmltopdf/packaging/releases/download/${version}-1/wkhtmltox_${version}-1.${distro}_amd64.deb"
  apt_install_deb "$url"
}

github_install_helper wkhtmltopdf "wkhtmltopdf/wkhtmltopdf"
