#!/usr/bin/env bash
source ../common.sh

say "installing prerequisites"
needs bashrc

say "installing lazy-cd (github)"
wget -qO ~/.bashrc.d/lcd.bashrc https://raw.githubusercontent.com/pedramamini/lazy-cd/master/lcd.sh

say "lazy-cd installation complete"
