#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/dannyben/eget/releases/download/v${version}/eget-${version}-linux_amd64.tar.gz"
  curl -sL "$url" | tar -xzv
  bin_install "eget"
  man_install "eget.1"
  popd
}

github_install_helper eget "dannyben/eget"
