#!/usr/bin/env bash
source ../common.sh

install_function() {
  needs fzf bashrc

  url="https://github.com/denisidoro/navi/releases/download/v${version}/navi-v${version}-x86_64-unknown-linux-musl.tar.gz"
  pushtmp
  wget "$url" -O "navi.tar.gz"
  tar -zxvf "navi.tar.gz" "navi"
  sudo install -m 755 "navi" /usr/local/bin/navi
  rm -f "navi.tar.gz"
  popd

  cp navi.bashrc ~/.bashrc.d/
  attention "restart your session or source ~/.bashrc"
}

github_install_helper navi "denisidoro/navi"
