#!/usr/bin/env bash
source ../common.sh

install_function() {
  apt_install_deb "https://github.com/cli/cli/releases/download/v$version/gh_${version}_linux_amd64.deb"
}

github_install_helper gh "cli/cli" "version"
