#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall github-cli ;;
  fedora|ubuntu)  package_uninstall gh ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
