#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|ubuntu)  package_install sshfs ;;
  fedora)              package_install fuse-sshfs ;;
  *)                   fail "not available for distro:$DISTRO" ;;
esac
