#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_install nmap ;;
  fedora)         package_install nmap-ncat ;;
  debian|ubuntu)  package_install ncat ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
