#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall nmap ;;
  fedora)         package_uninstall nmap-ncat ;;
  debian|ubuntu)  package_uninstall ncat ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
