#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_install aws-cli
    ;;
  "ubuntu")
    say "installing awscli (pip)"
    sudo pip install awscli
    ;;
esac
aws --version
