#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)    package_install zbar ;;
  debian|ubuntu)  package_install zbar-tools ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
