#!/usr/bin/env bash
source ../common.sh

if command_exist speedtest ; then
  say "speedtest is already installed"

else
  sudo apt-get install gnupg1 apt-transport-https dirmngr
  export INSTALL_KEY=379CE192D401AB61
  export DEB_DISTRO=$(lsb_release -sc)
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $INSTALL_KEY
  echo "deb https://ookla.bintray.com/debian ${DEB_DISTRO} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
  sudo apt-get update -y
  sudo apt-get install -y speedtest
  
  say "speedtest installaction complete"

fi
