#!/usr/bin/env bash
source ../common.sh

if command_exist speedtest ; then
  say "speedtest is already installed"

else
  sudo apt-get install gnupg1 apt-transport-https dirmngr
  install_key=379CE192D401AB61
  deb_distro=$(lsb_release -sc)
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $install_key
  echo "deb https://ookla.bintray.com/debian ${deb_distro} main" | sudo tee  /etc/apt/sources.list.d/speedtest.list
  sudo apt-get update -y
  sudo apt-get install -y speedtest
  
fi
