#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

install_function() {
  pushtmp
  url="https://github.com/mvdan/sh/releases/download/v${version}/shfmt_v${version}_linux_amd64"
  sudo wget -qO /usr/local/bin/shfmt "$url"
  sudo chmod +x /usr/local/bin/shfmt
  popd
}

github_install_helper shfmt mvdan/sh
