#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|fedora)  package_uninstall shfmt ;;
  ubuntu)              bin_uninstall shfmt ;;
  *)                   warning "not available for distro:$DISTRO" ;;
esac
