#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
case "$DISTRO" in
  "arch")
    package_install elixir
    ;;

  "ubuntu")
    say "installing elixir"
    wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
    sudo dpkg -i erlang-solutions_2.0_all.deb
    rm erlang-solutions_2.0_all*
    sudo apt-get -y update 
    sudo apt-get -y install esl-erlang elixir
    ;;
esac