#!/usr/bin/env bash
source ../common.sh
case "$DISTRO" in
  "arch")
    package_uninstall elixir
    ;;

  "ubuntu")
    say "uninstalling elixir"
    sudo dpkg -r erlang-solutions
    sudo apt-get -y remove elixir esl-erlang
    ;;
esac