#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)   package_install p7zip ;;
  fedora) package_install p7zip p7zip-plugins ;;
  ubuntu) package_install p7zip-full ;;
  *)      fail "not available for distro:$DISTRO" ;;
esac
