#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall p7zip ;;
  debian|ubuntu)  package_uninstall p7zip-full ;;
  fedora)         package_uninstall p7zip p7zip-plugins ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac

