#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

needs bashrc

# Add configuration file
say "copying ~/.bashrc.d/docker.bashrc"
cp docker.bashrc "$HOME/.bashrc.d/"

case "$DISTRO" in
  "arch")
    package_install docker
    package_install docker-compose
    package_install docker-buildx

    sudo usermod -aG docker "$(whoami)"

    attention "system reboot may be required"
    ;;

  "ubuntu")
    say "installing docker (setup script)"
    # Ideally, this would be the thing to run...
    # curl https://get.docker.com | sudo sh

    # ...but the stupid script sleeps for 20 seconds, and we don't want that
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sed -i 's/sleep 20/sleep 0/g' /tmp/get-docker.sh
    sh /tmp/get-docker.sh

    # Add user to group
    sudo usermod -aG docker "$(whoami)"
    sudo service docker start
    ;;

esac

