#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "removing ~/.bashrc.d/docker.bashrc"
rm -f "$HOME/.bashrc.d/docker.bashrc"

package_uninstall docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
