#!/usr/bin/env bash
source ../common.sh

case "$DISTRO" in
  "arch")
    say "removing ~/.bashrc.d/docker.bashrc"
    rm -f "$HOME/.bashrc.d/docker.bashrc"

    package_uninstall docker
    package_uninstall docker-compose
    package_uninstall docker-buildx
    
    ;;

  "ubuntu")
    say "not available in Ubuntu"

esac

