#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/sorenisanerd/gotty/releases/download/v${version}/gotty_v${version}_linux_amd64.tar.gz"
  
  pushtmp
  wget "$url" -O "gotty.tar.gz"
  tar -zxvf gotty.tar.gz
  sudo install -m 755 gotty /usr/local/bin/
  popd
  
  say "copying config"
  cp .gotty ~/.gotty
}

github_install_helper gotty sorenisanerd/gotty
