#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)    package_uninstall gitui ;;
  debian|ubuntu)  bin_uninstall gitui ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
