#!/usr/bin/env bash
source ../common.sh

install_function() {
  tmpdir=$(temp_dir)
  pushd "$tmpdir" 
  wget -O "syft-$version.tar.gz" "https://github.com/anchore/syft/releases/download/v$version/syft_${version}_linux_amd64.tar.gz"
  tar -xzvf "syft-$version.tar.gz"
  sudo cp syft /usr/local/bin/
  popd
  rm -rf "$tmpdir"
}

github_install_helper syft anchore/syft version
