#!/usr/bin/env bash
source ../common.sh

say "identifying latest version for docker/compose"
version=$(get_github_release_version docker/compose)
say "latest version is $version"

if ! is_installed docker-compose ; then
  say "installing docker-compose"
  sudo curl -L "https://github.com/docker/compose/releases/download/$version/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  say "docker-compose installation complete"

else
  say "installed version is also $version, no update needed."

fi
