#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/asciinema/agg/releases/download/v$version/agg-x86_64-unknown-linux-gnu"
  pushtmp
  wget -O agg "$url"
  sudo install agg /usr/local/bin/
  popd
}

github_install_helper agg asciinema/agg
