#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)          package_install aspell-en ;;
  fedora|ubuntu) package_install aspell ;;
  *)             fail "not available for distro:$DISTRO" ;;
esac
