#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_uninstall aspell-en ;;
  debian|fedora|ubuntu)  package_uninstall aspell ;;
  *)                     warning "not available for distro:$DISTRO" ;;
esac

