#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    package_install vim
    say "creating vi symlink"
    sudo ln -s /usr/bin/vim /usr/local/bin/vi
    ;;

  *)
    attention "not needed for $DISTRO"
    ;;
  
esac

