#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

case "$DISTRO" in
  "ubuntu")
    attention "not needed for Ubuntu"
    ;;
  "arch")
    package_install vim
    say "copying ~/.bashrc.d/vi.bashrc"
    cp vi.bashrc "$HOME/.bashrc.d/"
    ;;

esac

