#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    package_uninstall vim
    say "removing vi symlink"
    sudo rm -f /usr/local/bin/vi
    ;;

  *)
    warning "not available for distro:$DISTRO"
    ;;
  
esac

