#!/usr/bin/env bash
source ../common.sh

install_function() {
  wget "https://github.com/DarthSim/overmind/releases/download/v$version/overmind-v$version-linux-amd64.gz"
  gzip -d "overmind-v$version-linux-amd64.gz"
  sudo mv "overmind-v$version-linux-amd64" /usr/local/bin/overmind
  sudo chmod +x /usr/local/bin/overmind
}

github_install_helper overmind "DarthSim/overmind"
