#!/usr/bin/env bash
echo "Identifying latest version"
version=$(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
echo "Latest version is $version"

# If you want, force a version here
# version=1.1.9

echo "Comparing with installed version (if any)"
hash doctl 2> /dev/null && doctl version | head -n1 | grep $version > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  echo "Downloading doctl from GitHub..."
  curl -sL https://github.com/digitalocean/doctl/releases/download/v$version/doctl-$version-linux-amd64.tar.gz | tar -xzv

  chmod +x doctl
  sudo mv doctl /usr/local/bin/

  echo "Copying bash completion to bashrc.d"
  cp doctl.bashrc ~/.bashrc.d/doctl.bashrc

  echo "Done."
  doctl version

else
  echo "Installed version is also $version, no update needed."
  echo "Goodbye."

fi


