#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora) 
    package_uninstall doctl
    ;;
  
  ubuntu)
    bin_uninstall doctl
    rm ~/.bashrc.d/doctl.bashrc
    ;;

  *)
    warning "not available for distro:$DISTRO"
    ;;
esac
