#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora) 
    package_uninstall doctl
    ;;
  
  debian|ubuntu)
    bin_uninstall doctl
    remove_completions doctl
    ;;

  *)
    warning "not available for distro:$DISTRO"
    ;;
esac
