#!/usr/bin/env bash
source ../../common.sh

say "installing prerequisites"
needs alf

say "connecting alf to github repo"
wd=$PWD
cd /vagrant/bash
alf connect DannyBen/alf-conf -y
cd "$wd"

say "my/alf installation complete"
