#!/usr/bin/env bash
source ../../common.sh

if command_exist alf ; then
  say "skipping alf symlink, already exists"

else
  say "symlinking alf"
  sudo ln -s /vagrant/bash/alf/alf /usr/local/bin/alf

fi

say "updating ~/.alfrc"
echo /vagrant/bash/alf-conf > ~/.alfrc
