#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)  package_install sqlite ;;
  ubuntu)       package_install sqlite3 libsqlite3-dev ;;
  *)            fail "not available for distro:$DISTRO" ;;
esac
