#!/usr/bin/env bash
source ../common.sh

install_function() {
  sudo apt-add-repository -y ppa:zanchey/asciinema
  sudo apt-get -y update
  sudo apt-get -y install asciinema
}

general_install_helper asciinema
