#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

install_function() {
  sudo apt-add-repository -y ppa:zanchey/asciinema
  sudo apt-get -y update
  sudo apt-get -y install asciinema
}

case "$DISTRO" in
  "ubuntu") general_install_helper asciinema ;;
  "arch") package_install asciinema ;;
esac

