#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_install jre-openjdk ;;
  debian|ubuntu)  package_install default-jre ;;
  fedora)         package_install java-latest-openjdk ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac

java --version |head -n1