#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall jre-openjdk ;;
  debian|ubuntu)  package_uninstall default-jre ;;
  fedora)         package_uninstall java-latest-openjdk ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
