#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)   package_uninstall jre-openjdk ;;
  fedora) package_uninstall java-latest-openjdk ;;
  ubuntu) package_uninstall default-jre ;;
  *)      warning "not available for distro:$DISTRO" ;;
esac
