#!/usr/bin/env bash
source ../common.sh

# Reference: https://www.tangram.xyz/docs/install

install_function() {
  apt_install_deb "https://github.com/tangramdotdev/tangram/releases/download/v${version}/tangram_${version}_amd64.deb"
}

github_install_helper tangram "tangramdotdev/tangram"
