#!/usr/bin/env bash
source ../common.sh

# Reference: https://www.tangram.xyz/docs/install

install_function() {
  url="https://github.com/tangramdotdev/tangram/releases/download/v${version}/tangram_${version}_amd64.deb"
  apt_install_deb "$url"
}

github_install_helper tangram "tangramdotdev/tangram"
