#!/usr/bin/env bash
source ../common.sh

say "installing shellcheck (google)"
curl -o shellcheck.tzr.xz https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz

say "extracing archive"
tar -xf shellcheck.tzr.xz
rm shellcheck.tzr.xz

say "copying binary"
sudo mv shellcheck-stable/shellcheck /usr/local/bin/
sudo chmod +x /usr/local/bin/shellcheck

say "cleaning up"
rm -rf shellcheck-stable

shellcheck --version
say "shellcheck installation complete"
