#!/usr/bin/env bash
set -e

echo "Downloading config"
[[ -d ~/.ngrok2 ]] || mkdir ~/.ngrok2
wget -qO ~/.ngrok2/ngrok.yml $SELF/ngrok.yml

echo "Downloading binary (if necessary)"
[[ -x "$(command -v ngrok)" ]] || sudo snap install ngrok

echo "Done, installed version: $(ngrok version)"
