#!/usr/bin/env bash
set -e

echo "Identifying latest version"
version=$(curl -s https://api.github.com/repos/sharkdp/bat/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
echo "Latest version is $version"

echo "Comparing with installed version (if any)"
hash bat 2> /dev/null && bat --version | grep $version > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  echo "Downloading from GitHub..."
  wget -qO ./bat.deb https://github.com/sharkdp/bat/releases/download/v${version}/bat_${version}_amd64.deb
  sudo dpkg -i bat.deb 
  rm bat.deb

  echo "Copying config file to ~/.config/bat"
  mkdir -p ~/.config/bat
  cp config ~/.config/bat/config

  echo "Done."
  bat --version

else
  echo "Installed version is also $version, no update needed."
  echo "Goodbye."

fi


