#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/jesseduffield/lazydocker/releases/download/v$version/lazydocker_${version}_Linux_x86_64.tar.gz"
  
  pushtmp
  curl -sL "$url" | tar -xzv lazydocker
  chmod +x lazydocker
  sudo mv lazydocker /usr/local/bin/
  popd
}

github_install_helper lazydocker "jesseduffield/lazydocker"
