#!/usr/bin/env bash
source ../common.sh

install_function() {
  tmpdir=$(temp_dir)
  pushd "$tmpdir" 
  wget -O "grype-$version.tar.gz" "https://github.com/anchore/grype/releases/download/v$version/grype_${version}_linux_amd64.tar.gz"
  tar -xzvf "grype-$version.tar.gz"
  sudo cp grype /usr/local/bin/
  popd
  rm -rf "$tmpdir"
}

github_install_helper grype anchore/grype version
