#!/usr/bin/env bash
source ../common.sh

if command_exist solo ; then
  say "solo is already installed"

else
  say "installing solo (github)"
  curl -# -L https://raw.githubusercontent.com/DannyBen/solo/master/solo >/tmp/solo
  chmod +x /tmp/solo
  sudo mv /tmp/solo /usr/local/bin/

fi
