#!/usr/bin/env bash
source ../../common.sh

needs ipfs

say "creating ~/.bashrc.d/ipfs.bashrc"
cp ipfs.bashrc ~/.bashrc.d/

say "configuring ipfs daemon"
if [[ ! -d ~/.ipfs ]]; then
  ipfs init
fi

ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080

attention "restart your session or source ~/.bashrc.d/ipfs.bashrc"
