#!/usr/bin/env bash
source ../common.sh

needs bashrc

if command_exist rbenv ; then
  say "rbenv is already installed, upgrading"
  git -C "$(rbenv root)" pull
  git -C "$(rbenv root)"/plugins/ruby-build pull

else
  say "installing rbenv to ~/.rbenv"
  git clone --depth 1 https://github.com/rbenv/rbenv.git ~/.rbenv

  say "copying bashrc.d config"
  cp rbenv.bashrc ~/.bashrc.d/
  source rbenv.bashrc

  say "installing ruby-build plugin"
  mkdir -p "$(rbenv root)"/plugins
  git clone --depth 1 https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

  say "rvm installation complete"
  say "restart your session for rvm to be enabled"
  say "(or source ~/.bashrc.d/rbenv.bashrc)"

fi