#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs bashrc

if command_exist rbenv ; then
  say "rbenv is already installed, upgrading"
  git -C "$(rbenv root)" pull
  git -C "$(rbenv root)"/plugins/ruby-build pull

else
  case "$DISTRO" in
    "ubuntu")
      # Note: This also installs the apt version of Ruby
      # It appears it is needed for ruby-build to work...
      # ref: https://github.com/rubyomr-preview/rubyomr-preview/issues/22
      say "installing system ruby with apt"
      sudo apt install -y ruby
      ;;
  esac

  say "installing rbenv to ~/.rbenv"
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv

  say "copying bashrc.d config"
  cp rbenv.bashrc ~/.bashrc.d/
  # shellcheck disable=SC1091,SC1090
  source "$HOME/.bashrc.d/rbenv.bashrc"

  say "installing ruby-build plugin"
  mkdir -p "$(rbenv root)"/plugins
  git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build

  say "rbenv installation complete"
  attention "restart your session or source ~/.bashrc.d/rbenv.bashrc"

fi
