#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

package_install resolvconf

say "copying configuration file"
sudo cp configs/resolv.conf /etc/resolv.conf

sudo service resolvconf restart
cat /etc/resolv.conf
attention "reboot may be required"
