#!/usr/bin/env bash
source ../common.sh

case "$DISTRO" in
  "arch")
    attention "not available for Arch Linux"
    ;;
  "ubuntu")
    say "uninstalling python3-venv"
    sudo apt remove -y python3-venv

    say "uninstalling pipenv"
    python3 -m pip uninstall pipenv
    ;;
esac
