#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
eget_install dannyben/ssi
ssi install completion "https://raw.githubusercontent.com/DannyBen/ssi/refs/tags/v$(ssi --version)/completions/ssi" --shell bash
