#!/usr/bin/env bash
# Script adapted from https://github.com/scheib/chromium-latest-linux

source ../common.sh

target=/opt/chrome
say "identifying latest revision"

url="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media"
revision=$(curl -s -S "$url")
say "latest revision is $revision"

if [[ -d "$target/$revision" ]] ; then
  say "latest revision already installed ($target), aborting"
  exit
fi

url="https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F$revision%2Fchrome-linux.zip?alt=media"
zipfile="chrome.zip"
say "downloading chrome from $url"

curl -# "$url" > "$zipfile"

say "unzipping to $target"
sudo mkdir -p "$target"
sudo unzip "$zipfile" -d "$target"
sudo mv "$target/chrome-linux" "$target/$revision"
sudo rm -f "$target/latest"
sudo ln -s "$target/$revision" "$target/latest"
sudo rm -f "/usr/local/bin/chrome"
sudo ln -s "$target/latest/chrome" "/usr/local/bin/chrome"

say "cleaning up"
rm chrome.zip

chrome --version
say "done"
