#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch | debian | fedora) package_uninstall chromium ;;
  ubuntu) package_uninstall google-chrome-stable ;;
  *) warning "not available for distro:$DISTRO" ;;
esac
