#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_uninstall chromium
    ;;

  "ubuntu")
    say "uninstalling chrome"
    sudo rm -rf /opt/chrome
    sudo rm -rf /usr/local/bin/chrome
    ;;
esac

