#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

install_function() {
  apt_install_deb "https://github.com/rclone/rclone/releases/download/v${version}/rclone-v${version}-linux-amd64.deb"
}

case "$DISTRO" in
  "ubuntu") github_install_helper rclone rclone/rclone ;;
  "arch") package_install rclone ;;
esac
