#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/rclone/rclone/releases/download/v${version}/rclone-v${version}-linux-amd64.deb"
  apt_install_deb "$url"
}

github_install_helper rclone rclone/rclone
