#!/usr/bin/env bash
source ../common.sh

if command_exist brew ; then
  say "homebrew is already installed"

else
  needs bashrc

  say "running homebrew install script"
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  
  say "copying bashrc.d config"
  cp homebrew.bashrc ~/.bashrc.d/

  attention "restart your session or source ~/.bashrc to apply changes"
  
fi
