#!/usr/bin/env bash
source ../common.sh

if command_exist brew ; then
  say "homebrew is already installed"

else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  
fi
