#!/usr/bin/env bash
source ../common.sh

if command_exist brew ; then
  say "running homebrew uninstall script"
  pushtmp
  wget https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh
  bash uninstall.sh --force

  say "removing bashrc.d config"
  rm -f ~/.bashrc.d/homebrew.bashrc
  popd

else
  say "homebrew is not installed"
  
fi
