#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

needs python

say "installing shopify themekit (install script)"
curl -s https://shopify.github.io/themekit/scripts/install.py | sudo python
theme version
