#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing prerequisites"
package_install libfontconfig

pushtmp
say "installing phantomjs"
wget -O phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2

say "extracting archive"
tar xvjf phantomjs.tar.bz2

say "copying binary"
sudo cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
sudo chmod +x /usr/local/bin/phantomjs

say "cleaning up"
rm phantomjs.tar.bz2
rm -rf phantomjs-2.1.1-linux-x86_64
popd

phantomjs --version
