#!/usr/bin/env bash
source ../../common.sh

warning "this package is currently blocked since it requires too many dependencies"

# echo "Installing yarn if necessary"
# [[ -x "$(command -v yarn)" ]] || rush get "$REPO:yarn"

# echo "installing terminalizer"
# yarn global add terminalizer

