#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

needs bashrc
command_exist fzf || needs fzf

say "installing fuzzy-cd"
sudo wget -qO /usr/local/bin/fuzzycd https://raw.githubusercontent.com/DannyBen/fuzzycd/master/fuzzycd
sudo chmod +x /usr/local/bin/fuzzycd

say "copying bashrc.d config"
cp fuzzycd.bashrc ~/.bashrc.d/

attention "restart your session or source ~/.bashrc"
