#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "uninstalling fuzzycd"
sudo rm -rf /usr/local/bin/fuzzycd
rm -f ~/.bashrc.d/fuzzycd.bashrc
attention "restart your session for a a complete uninstall"
