#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  dnf_install_rpm "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm"
}

github_install_helper cloudflared cloudflare/cloudflared
