#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  apt_install_deb "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
}

github_install_helper cloudflared cloudflare/cloudflared
