#!/usr/bin/env bash
set -e
echo "Installing Rust"
curl https://sh.rustup.rs -sSf | sh

echo "Configuring rust.bashrc"
cp rust.bashrc ~/.bashrc.d/rust.bashrc

echo "Installed rust version:"
rustc --version

echo "Done. Restart your terminal or run:"
echo "source ~/.cargo/env"

echo "To uninstall run:"
echo "rustup self uninstall"