#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_uninstall dog
    ;;

  "ubuntu")
    bin_uninstall dog
    sudo rm -f /usr/local/share/man/man1/dog.1
    sudo rm -f /usr/share/bash-completion/completions/dog
    ;;
esac
