#!/usr/bin/env bash
set -ex
sudo wget -qO /usr/local/bin/rush \
https://raw.githubusercontent.com/DannyBen/rush/master/rush && \
sudo chmod +x /usr/local/bin/rush
wget -qO ~/.bashrc.d/rush.bashrc $SELF/rush.bashrc
