#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/KSXGitHub/parallel-disk-usage/releases/download/$version/pdu-x86_64-unknown-linux-gnu"
  wget -O pdu "$url"
  sudo install -m 755 pdu /usr/local/bin/
  popd
}

github_install_helper pdu KSXGitHub/parallel-disk-usage
