#!/usr/bin/env bash
source ../common.sh

# ref: https://github.com/nodesource/distributions#installation-instructions
say "installing node (setup script + apt)"
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install nodejs -y

# ref: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
say "configuring global node directory in ~/.npm-global"
mkdir -p ~/.npm-global
npm config set prefix "$HOME/.npm-global"
cp node.bashrc ~/.bashrc.d/

attention "restart your session or source ~/.bashrc"
node -v
