#!/usr/bin/env bash
source ../common.sh

say "installing node (setup script + apt)"
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install nodejs -y
node -v
say "node installation complete"
