#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "ubuntu")
    package_uninstall nodejs
    ;;

  "arch")
    package_uninstall nodejs
    package_uninstall npm
    ;;

esac

rm -rf ~/.npm-global
rm -f ~/.bashrc.d/node.bashrc
