#!/usr/bin/env bash
source ../common.sh

install_function() {
  apt_install_deb "https://github.com/Orange-OpenSource/hurl/releases/download/${version}/hurl_${version}_amd64.deb"
}

github_install_helper hurl Orange-OpenSource/hurl
