#!/usr/bin/env bash
# ref: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
source ../common.sh

say "installing kubectl (google)"
curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
say "kubectl installation complete"
# cp kubectl.bashrc ~/.bashrc.d/
