#!/usr/bin/env bash
# ref: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
source ../common.sh

say "installing kubectl (google)"
sudo curl --output /usr/local/bin/kubectl -L "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
sudo chmod +x /usr/local/bin/kubectl
# cp kubectl.bashrc ~/.bashrc.d/

