#!/usr/bin/env bash
# ref: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
set -e

curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
kubectl version --short
# cp kubectl.bashrc ~/.bashrc.d/
