#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall kubectl ;;
  debian|fedora)  package_uninstall kubernetes-client ;;
  ubuntu)         bin_uninstall kubectl ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
