#!/usr/bin/env bash

echo "Identifying latest version"
version=$(curl -s https://api.github.com/repos/wagoodman/dive/releases/latest | grep "tag_name" | cut -d : -f 2,3 | tr -d \"\ ,v)
echo "Latest version is $version"

echo "Comparing with installed version (if any)"
hash dive 2> /dev/null && dive --version | grep $version > /dev/null 2>&1

if [[ "$?" != "0" ]]; then
  echo "Downloading binary"
  wget https://github.com/wagoodman/dive/releases/download/v${version}/dive_${version}_linux_amd64.deb
  sudo apt install ./dive_${version}_linux_amd64.deb
  rm ./dive_${version}_linux_amd64.deb

  echo "Copying config file to ~/.dive.yaml"
  cp .dive.yaml ~/.dive.yaml

  echo "Done. "

else
  echo "Installed version is also $version, no update needed."
  echo "Goodbye."

fi


