#!/usr/bin/env bash
source ../common.sh

needs bashrc

say "installing nnn (apt)"
sudo apt install nnn

say "copying bashrc.d config"
cp nnn.bashrc ~/.bashrc.d/nnn.bashrc

nnn -v
say "nnn installation complete"
