#!/usr/bin/env bash
# Source: https://github.com/docker/machine/releases

set -e

VERSION=0.16.1
curl -# -L https://github.com/docker/machine/releases/download/v$VERSION/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
  chmod +x /tmp/docker-machine &&
  sudo mv /tmp/docker-machine /usr/local/bin/docker-machine