#!/usr/bin/env bash
source ../common.sh

say "uninstalling docker-machine"
sudo rm -f /usr/local/bin/docker-machine
sudo rm -f /etc/bash_completion.d/docker-machine-wrapper.bash
sudo rm -f /etc/bash_completion.d/docker-machine.bash
