#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    needs binpath
    package_install python-pipx
    ;;
  debian|fedora|ubuntu)
    needs binpath
    package_install pipx
    ;;
  *)
    fail "not available for distro:$DISTRO"
    ;;
esac
