#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  fedora)         package_uninstall v8 ;;
  debian|ubuntu)  package_uninstall libv8-dev ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
