#!/usr/bin/env bash
source ../common.sh

install_function() {
  download_url="https://github.com/allcloud-io/clisso/releases/download/${version}/clisso_linux_amd64.zip"

  pushtmp
  wget --no-verbose -O download.zip "$download_url"
  unzip download.zip clisso
  sudo install -m0755 clisso /usr/local/bin/
  rm -f download.zip
  rm -f clisso
  popd
}

needs unzip
github_install_helper clisso "allcloud-io/clisso" "version"
