#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_uninstall coffeescript
    ;;

  "ubuntu")
    say "uninstalling coffeescript"
    yarn global remove coffeescript
    ;;
esac
