#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

command_exist cloudflared || needs cloudflared

say "copying service configuration file"
sudo cp cloudflared-proxy-dns.service /etc/systemd/system/

say "copying DNS configuration file"
sudo mkdir -p /etc/systemd/resolved.conf.d
sudo cp resolved.conf /etc/systemd/resolved.conf.d/dns.conf
sudo chmod 644 /etc/systemd/resolved.conf.d/dns.conf

say "enabling cloudflared-proxy-dns"
sudo systemctl enable --now cloudflared-proxy-dns

say "restarting systemd-resolved"
sudo systemctl restart systemd-resolved

say "done"
resolvectl status