#!/usr/bin/env bash
source ../common.sh

install_function() {
  pushtmp
  url="https://github.com/joseluisq/static-web-server/releases/download/v$version/static-web-server-v${version}-x86_64-unknown-linux-gnu.tar.gz"
  curl -sL "$url" | tar -xzv --strip-components 1
  sudo install static-web-server /usr/local/bin/
  popd
}

github_install_helper static-web-server "joseluisq/static-web-server"
