#!/usr/bin/env bash
set -ex

curl -sSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash

curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add -
echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
sudo apt-get update

sudo apt install crystal

### Optionals
# sudo apt install libssl-dev      # for using OpenSSL
# sudo apt install libxml2-dev     # for using XML
# sudo apt install libyaml-dev     # for using YAML
# sudo apt install libgmp-dev      # for using Big numbers
# sudo apt install libreadline-dev # for using Readline
# sudo apt install libz-dev        # for using crystal play