#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall go ;;
  debian|fedora)  package_uninstall golang ;;
  ubuntu)         bin_uninstall go ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac

say "removing bashrc.d config"
rm -f ~/.bashrc.d/go.bashrc