#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                 package_uninstall go ;;
  debian|ubuntu|fedora) package_uninstall golang ;;
  *) warning "not available for distro:$DISTRO" ;;
esac

say "removing bashrc.d config"
rm -f ~/.bashrc.d/go.bashrc
