#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    package_uninstall go
    ;;

  fedora)
    package_uninstall golang
    ;;
  
  ubuntu)
    bin_uninstall go
    rm ~/.bashrc.d/go.bashrc
    ;;

  *)
    warning "not available for distro:$DISTRO"
    ;;
esac
