#!/usr/bin/env bash
source ../common.sh

needs bashrc


say "installing opcode (github)"
sudo wget -qO /usr/local/bin/op https://raw.githubusercontent.com/DannyBen/opcode/master/op
sudo chmod +x /usr/local/bin/op

say "copying bashrc.d config"
cp opcode.bashrc ~/.bashrc.d/opcode.bashrc

op --version
