#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

say "installing opcode"

if [[ -f ~/.bashrc.d/opcode.bashrc ]]; then
  say "cleaning up previous installation"
  rm ~/.bashrc.d/opcode.bashrc
fi

bash <(curl -Ls get.dannyb.co/opcode/setup)
op --version
