#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch") package_uninstall zellij ;;
  "ubuntu") bin_uninstall zellij ;;
esac

say "removing ~/.config/zellij"
rm -rf ~/.config/zellij
