#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_uninstall zellij ;;
  debian|fedora|ubuntu)  bin_uninstall zellij ;;
  *)                     warning "not available for distro:$DISTRO" ;;
esac

say "removing ~/.config/zellij"
rm -rf ~/.config/zellij
