#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "updating package manager"
needs update

say "installing prerequisites"
needs curl git wget eza

say "installing configuration"
needs my/cdpath my/gitconfig my/hostname my/bashrc
needs dircolors vimrc inputrc toprc locale ssh-agent prompt/dollar-color

say "installing alf"
needs my/alf 

say "installing tools"
needs vi fd less ripgrep bash-completion

say "my/bootstrap complete"
attention "you may need to restart your session"
