#!/usr/bin/env bash
source ../../common.sh

say "installing my/* packages"
needs my/bashrc my/cdpath my/gitconfig my/bash-completion my/alf

say "installing public packages"
needs dircolors exrc inputrc toprc locale ssh-agent prompt/dollar-color

say "my/bootstrap complete"
attention "you may need to restart your session"
