#!/usr/bin/env bash
source ../common.sh

say "installing rush"

if [[ -f ~/.bashrc.d/rush.bashrc ]]; then
  say "cleaning up previous installation"
  rm ~/.bashrc.d/rush.bashrc
fi

say "rush will update in the background in a moment"
( sleep 1 && bash <(curl -Ls get.dannyb.co/rush/setup) > /dev/null ) &
