#!/usr/bin/env bash

set -e

sudo apt-get install software-properties-common
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get update
sudo apt-get install rvm
sudo usermod -a -G rvm "$(whoami)"

echo "Done."
echo "Restart your session for RVM to be enabled."

