#!/usr/bin/env bash
source ../common.sh

if command_exist rvm ; then
  say "rvm is already installed"
  say "run 'rvm get stable' to upgrade"

else
  say "installing rvm (apt)"
  sudo apt-get install -y software-properties-common
  sudo apt-add-repository -y ppa:rael-gc/rvm
  sudo apt-get update -y
  sudo apt-get install -y rvm
  sudo usermod -a -G rvm "$(whoami)"
  cp .rvmrc ~/

  say "rvm installation complete"
  say "restart your session for rvm to be enabled"

fi