#!/usr/bin/env bash
source ../../common.sh

warning "this package is deprecated since it is no longer maintained."

# echo "Installing yarn if necessary"
# [[ -x "$(command -v yarn)" ]] || rush get "$REPO:yarn"

# echo "installing ttystudio"
# sudo yarn global add ttystudio

