#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|ubuntu)  package_install imagemagick ;;
  fedora)              package_install ImageMagick ;;
  *)                   fail "not available for distro:$DISTRO" ;;
esac

convert --version | head -n1
