#!/usr/bin/env bash
source ../common.sh

if command_exist python3 && command_exist pip3 ; then
  say "python3 and pip3 are already installed"

else
  say "installing python3 and pip3 (apt)"
  sudo apt install -y python3 python3-pip

fi

if ! command_exist python ; then
  say "symlinking python => python3"
  sudo ln -s /usr/bin/python3 /usr/bin/python
fi

if ! command_exist pip ; then
  say "symlinking pip => pip3"
  sudo ln -s /usr/bin/pip3 /usr/bin/pip
fi
