#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_install bind ;;
  debian|ubuntu)  package_install bind9-host ;;
  fedora)         package_install bind-utils ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac

