#!/usr/bin/env bash
source ../common.sh

if command_exist yarn ; then
  say "yarn is already installed"

else
  say "installing prerequisites"
  needs node bashrc

  say "installing yarn (apt)"
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt-get update -y
  sudo apt-get install -y yarn

  say "copying bashrc.d configuration"
  cp yarn.bashrc ~/.bashrc.d/yarn.bashrc

  yarn --version
  say "yarn installation complete"

fi
