#!/usr/bin/env bash
set -e

if hash yarn 2> /dev/null; then
  echo "Yarn is already installed, Goodbye."

else
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  sudo apt-get update && sudo apt-get install yarn -y

fi
