#!/usr/bin/env bash
set -e

[[ -x "$(command -v node)" ]] || rush get $REPO node

echo "Installing Yarn"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn -y

echo "Copying bashrc.d PATH extenention"
cp yarn.bashrc ~/.bashrc.d/yarn.bashrc

echo "Done"
