#!/usr/bin/env bash

set -e

echo "This package is deprecated since it is no longer maintained."

# echo "Installing yarn if necessary"
# [[ -x "$(command -v yarn)" ]] || rush $REPO yarn

# echo "installing ttystudio"
# sudo yarn global add ttystudio

