#!/usr/bin/env bash
source ../common.sh

say "installing prerequisites"
needs python

say "installing termtosvg (pip)"
sudo pip3 install --upgrade termtosvg

termtosvg -h | head -n2
say "termtosvg installation complete"
