#!/usr/bin/env bash
set -e

echo "Installing pip3 if necessary"
[[ -x "$(command -v pip3)" ]] || rush get $REPO python

echo "Installing termtosvg"
sudo pip3 install --upgrade termtosvg

# there is no termtosvg --version, so we do this instead to verify install:
termtosvg -h | head -n2

echo "Done"
