#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora) package_install the_silver_searcher ;;
  ubuntu)      package_install silversearcher-ag ;;
  *)           fail "not available for distro:$DISTRO" ;;
esac
