#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora) package_uninstall the_silver_searcher ;;
  ubuntu)      package_uninstall silversearcher-ag ;;
  *)           warning "not available for distro:$DISTRO" ;;
esac
