#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  url="https://github.com/terrastruct/TALA/releases/download/v${version}/tala-v${version}-linux-amd64.tar.gz"
  curl -sL "$url" | tar -xzv
  sudo install -m 755 "tala-v$version/bin/d2plugin-tala" /usr/local/bin/
  man_install "tala-v$version/man/d2plugin-tala.1"
  popd
}

github_install_helper d2plugin-tala terrastruct/TALA
