#!/usr/bin/env bash
source ../common.sh

if command_exist gpg2 ; then
  say "gpg2 is already installed"

else
  say "installing gpg2 (apt)"
  sudo apt-get install -y gnupg2

  say "copying bashrc.d config"
  cp gpg2.bashrc ~/.bashrc.d/

fi

