#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_install gnupg ;;
  debian|fedora|ubuntu)  package_install gnupg2 ;;
  *)                     fail "not available for distro:$DISTRO" ;;
esac

needs bashrc
say "copying bashrc.d config"
cp gpg2.bashrc ~/.bashrc.d/
