#!/usr/bin/env bash
source ../common.sh

if command_exist gpg2 ; then
  say "gpg2 is already installed"

else
  case "$DISTRO" in
    "ubuntu") package_install gnupg2 ;;
    "arch") package_install gnupg ;;
  esac

  say "copying bashrc.d config"
  cp gpg2.bashrc ~/.bashrc.d/

fi

