#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)    package_uninstall libwebp ;;
  debian|ubuntu)  package_uninstall webp ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac
