#!/usr/bin/env bash
# ref: https://linuxconfig.org/how-to-install-cuda-on-ubuntu-20-04-focal-fossa-linux
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  acrh)   package_uninstall cuda ;;
  ubuntu) package_uninstall nvidia-cuda-toolkit ;;
  *)      warning "not available for distro:$DISTRO" ;;
esac