#!/usr/bin/env bash
# ref: https://linuxconfig.org/how-to-install-cuda-on-ubuntu-20-04-focal-fossa-linux
source "$REPO_PATH/boot.sh"

case "$DISTRO" in
  "ubuntu") package_uninstall nvidia-cuda-toolkit ;;
  "acrh") package_uninstall cuda ;;
esac