#!/usr/bin/env bash
set -e

echo "Installing pip3 if necessary"
[[ -x "$(command -v pip3)" ]] || rush get $REPO python

echo "Installing youtube-dl"
sudo pip3 install --upgrade youtube-dl
youtube-dl --version

echo "Done"
