#!/usr/bin/env bash
source ../common.sh

install_function() {
  needs ffmpeg
  url="https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp"

  sudo wget -O /usr/local/bin/youtube-dl "$url"
  sudo chmod +x /usr/local/bin/youtube-dl
}

github_install_helper youtube-dl "yt-dlp/yt-dlp"
