#!/usr/bin/env bash
source ../common.sh

say "installing prerequisites"
needs python

say "installing youtube-dl (pip)"
sudo pip3 install --upgrade youtube-dl

youtube-dl --version
say "youtube-dl installation complete"
