#!/usr/bin/env bash
source ../common.sh

install_function() {
  pushtmp
  url="https://github.com/containers/podman/releases/download/v${version}/podman-remote-static-linux_amd64.tar.gz"
  curl -sL "$url" | tar -xzv
  sudo install -m 755 ./bin/podman-remote-static-linux_amd64 /usr/local/bin/podman
  popd
}

github_install_helper podman containers/podman
