#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

# needs bashrc
package_install tmux

say "copying configuration files"
cp .tmux.conf ~/.tmux.conf
# cp tmux.bashrc ~/.bashrc.d/
# tmux bashrc config is not needed if using keychain

say "installing tmux plugin manager (tpm)"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
