#!/usr/bin/env bash
set -ex

sudo apt-get install tmux -y
wget -qO ~/.tmux.conf $SELF/.tmux.conf
wget -qO ~/.bashrc.d/tmux.bashrc $SELF/tmux.bashrc
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
