#!/usr/bin/env bash
source ../common.sh

install_function() {
  curl -sL "https://github.com/cjbassi/ytop/releases/download/$version/ytop-$version-x86_64-unknown-linux-gnu.tar.gz" | tar -xzv
  chmod +x ytop
  sudo mv ytop /usr/local/bin/
}

github_install_helper ytop "cjbassi/ytop"
