#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)
    sudo pacman -Syu --noconfirm
    ;;

  fedora)
    sudo dnf upgrade -y
    ;;

  debian|ubuntu)
    sudo DEBIAN_FRONTEND=noninteractive apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
      -o Dpkg::Options::="--force-confdef" \
      -o Dpkg::Options::="--force-confold"
    sudo DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
    ;;

  *)
    fail "not available for distro: $DISTRO"
    ;;
esac
