#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_install apache ;;
  debian|ubuntu)  package_install apache2-utils ;;
  fedora)         package_install httpd-tools ;;
  *)              fail "not available for distro:$DISTRO" ;;
esac
