#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)           package_uninstall apache ;;
  debian|ubuntu)  package_uninstall apache2-utils ;;
  fedora)         package_uninstall httpd-tools ;;
  *)              warning "not available for distro:$DISTRO" ;;
esac

