#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)  package_install poppler ;;
  ubuntu)       package_install poppler-utils ;;
  *)            fail "not available for distro:$DISTRO" ;;
esac
