#!/usr/bin/env bash
source ../common.sh

say "installing crypto (github)"
sudo wget -qO /usr/local/bin/crypto https://raw.githubusercontent.com/DannyBen/crypto-cli/master/crypto
sudo chmod +x /usr/local/bin/crypto
