#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

say "installing crypto (github)"
sudo wget -qO /usr/local/bin/crypto https://raw.githubusercontent.com/DannyBen/crypto-cli/master/crypto
sudo chmod +x /usr/local/bin/crypto
