#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|fedora)  package_uninstall hub ;;
  ubuntu)              bin_uninstall hub ;;
  *)                   warning "not available for distro:$DISTRO" ;;
esac
