#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  "arch")
    package_uninstall postgresql
    ;;
  "ubuntu")
    package_uninstall postgresql
    package_uninstall libpq-dev
    ;;
esac