#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|fedora)  package_uninstall postgresql ;;
  ubuntu)       package_uninstall postgresql libpq-dev ;;
  *)            warning "not available for distro:$DISTRO" ;;
esac