#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch|debian|fedora)  package_install php ;;
  ubuntu)              package_install php7.4-cli ;;
  *)                   fail "not available for distro:$DISTRO" ;;
esac
