#!/usr/bin/env bash
source ../common.sh

install_function() {
  apt_install_deb "https://github.com/sharkdp/hexyl/releases/download/v$version/hexyl_${version}_amd64.deb"
}

github_install_helper hexyl "sharkdp/hexyl"
