#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  apt_install_deb "https://github.com/sharkdp/hexyl/releases/download/v$version/hexyl_${version}_amd64.deb"
}

case "$DISTRO" in
  "ubuntu") github_install_helper hexyl sharkdp/hexyl ;;
  "arch") package_install hexyl ;;
esac
