#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

say "installing alf (github)"
sudo wget -qO /usr/local/bin/alf https://raw.githubusercontent.com/DannyBen/alf/master/alf
sudo chmod +x /usr/local/bin/alf
alf --version
