#!/usr/bin/env bash
source ../common.sh

if command_exist flynn ; then
  say "flynn is already installed"

else
  say "installying flynn"
  curl -sSL -O -A "`uname -sp`" https://dl.flynn.io/cli
  zcat cli > /tmp/flynn
  sudo install /tmp/flynn /usr/local/bin/flynn
  rm cli

  flynn --version

fi
