#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

install_function() {
  pushtmp
  needs bashrc

  url="https://github.com/spinel-coop/rv/releases/download/v${version}/rv-x86_64-unknown-linux-gnu.tar.xz"

  curl -sL "$url" | tar -xJ --strip-components=1
  sudo install -m 755 rv rvx /usr/local/bin/
  popd

  say "copying shell configuration"
  cp rv.bashrc ~/.bashrc.d/

  say "creating bash completions"
  source rv.bashrc
  mkdir -p ~/.local/share/bash-completion/completions
  rv shell completions bash > ~/.local/share/bash-completion/completions/rv

  attention "restart your session or source ~/.bashrc"
}

github_install_helper rv spinel-coop/rv
