#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
needs bashrc bash-completion

eget_install spinel-coop/rv

say "copying shell configuration"
cp rv.bashrc ~/.bashrc.d/

say "creating bash completions"
source rv.bashrc
mkdir -p ~/.local/share/bash-completion/completions
rv shell completions bash > ~/.local/share/bash-completion/completions/rv

attention "restart your session or source ~/.bashrc"
