#!/usr/bin/env bash
source ../common.sh

file=/etc/systemd/resolved.conf
say "configuring $file"
sudo sed -i 's/^#DNS=.*/DNS=1.1.1.1 8.8.8.8/g' "$file"
attention "you need to reboot for changes to take effect"
