#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"
say "configuring locale"
if command_exist localectl; then
  sudo localectl set-locale LANG=en_US.UTF-8
else
  warning "cannot configure locale without localectl"
fi
