#!/usr/bin/env bash
source ../common.sh
say "installing redis client and server"
case "$DISTRO" in
  "ubuntu")
    package_install redis-server
    package_install redis-tools redis-cli
    ;;

  "arch")
    package_install redis
    sudo systemctl start redis
    ;;
esac
