#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

eget_install "whalebrew/whalebrew"

say "creating config file in ~/.whalebrew"
mkdir -p "$HOME/.whalebrew"
echo "install_path: $HOME/.local/bin" > "$HOME/.whalebrew/config.yaml"

