#!/usr/bin/env bash
source "$REPO_PATH/boot.sh"

install_function() {
  apt_install_deb "https://github.com/sharkdp/fd/releases/download/v$version/fd_${version}_amd64.deb"
}

case "$DISTRO" in
  "ubuntu") github_install_helper fd sharkdp/fd ;;
  "arch") package_install fd ;;
esac
