#!/usr/bin/env bash
source ../common.sh

install_function() {
  url="https://github.com/tsl0922/ttyd/releases/download/${version}/ttyd.x86_64"
  
  pushtmp
  wget "$url" -O "ttyd"
  sudo install -m 755 ttyd /usr/local/bin/
  popd
}

github_install_helper ttyd tsl0922/ttyd
