#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_uninstall ttyd ;;
  fedora|debian|ubuntu)  bin_uninstall ttyd ;;
  *)                     warning "not available for distro:$DISTRO" ;;
esac
