#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

if [[ -z $FORCE ]] && command_exist check-jsonschema ; then
  say "check-jsonschema is already installed"
else
  needs pipx
  pipx install check-jsonschema
fi
