#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

# The arch package is broken
# package_install check-jsonschema

if command_exist check-jsonschema ; then
  say "check-jsonschema is already installed"
else
  needs pipx
  pipx install check-jsonschema
fi

