#!/usr/bin/env bash
source "$REPO_PATH/lib.sh"

case "$DISTRO" in
  arch)                  package_uninstall curlie ;;
  debian|fedora|ubuntu)  bin_uninstall curlie ;;
  *)                     warning "not available for distro:$DISTRO" ;;
esac
