name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update shellcheck
      run: sudo apt-get install -y shellcheck

    - name: Run tests
      run: ./test.sh
